"""
Utility functions for AI Stock Market Analyzer
Includes data type conversion and PDF generation functionality
"""

import json
import numpy as np
import pandas as pd
from datetime import datetime, date
from io import BytesIO
from reportlab.lib import colors
from reportlab.lib.pagesizes import A4
from reportlab.platypus import (
    SimpleDocTemplate,
    Table,
    TableStyle,
    Paragraph,
    Spacer
)
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.units import inch
import logging


# ============================================================
# NUMPY / PANDAS SAFE CONVERSION
# ============================================================

def convert_numpy_types(obj):
    """
    Recursively convert numpy / pandas data types
    into native Python types (DB + JSON safe)
    """
    if isinstance(obj, dict):
        return {k: convert_numpy_types(v) for k, v in obj.items()}
    elif isinstance(obj, list):
        return [convert_numpy_types(i) for i in obj]
    elif isinstance(obj, tuple):
        return tuple(convert_numpy_types(i) for i in obj)
    elif isinstance(obj, np.integer):
        return int(obj)
    elif isinstance(obj, np.floating):
        return float(obj)
    elif isinstance(obj, np.ndarray):
        return obj.tolist()
    elif isinstance(obj, (np.bool_, bool)):
        return bool(obj)
    elif isinstance(obj, (datetime, date)):
        return obj
    elif pd.isna(obj):
        return None
    return obj


def serialize_prediction_data(data):
    """
    Serialize prediction data safely into JSON
    """
    try:
        return json.dumps(convert_numpy_types(data), indent=2, default=str)
    except Exception as e:
        logging.error(f"Serialization error: {e}")
        return json.dumps({"error": "Serialization failed"})


def format_time_horizon(value):
    """
    Normalize time horizon for PDF display
    Accepts:
      - "1 Day"
      - "2 Weeks"
      - "3 Months"
      - "1 Year"
    """
    if not value:
        return "N/A"

    value = str(value).strip()
    return value.replace("_", " ").title()

def generate_prediction_pdf(prediction_data, prediction_type="stock_prediction"):
    """
    Generate a professional PDF report for predictions
    """
    buffer = BytesIO()

    doc = SimpleDocTemplate(
        buffer,
        pagesize=A4,
        rightMargin=72,
        leftMargin=72,
        topMargin=72,
        bottomMargin=36
    )

    styles = getSampleStyleSheet()

    title_style = ParagraphStyle(
        name="TitleStyle",
        parent=styles["Heading1"],
        alignment=1,
        fontSize=18,
        spaceAfter=20,
        textColor=colors.darkgreen
    )

    heading_style = ParagraphStyle(
        name="HeadingStyle",
        parent=styles["Heading2"],
        fontSize=14,
        spaceAfter=10,
        textColor=colors.darkblue
    )

    content = []

    # -------- TITLE --------
    title_map = {
        "stock_prediction": "Stock Price Prediction Report",
        "investment_prediction": "Investment Profitability Report",
        "company_comparison": "Company Comparison Report"
    }

    content.append(Paragraph(
        title_map.get(prediction_type, "AI Stock Analysis Report"),
        title_style
    ))

    timestamp = datetime.now().strftime("%B %d, %Y at %I:%M %p")
    content.append(Paragraph(f"Generated on: {timestamp}", styles["Normal"]))
    content.append(Spacer(1, 20))

    # -------- BODY --------
    if prediction_type == "stock_prediction":
        content.extend(_add_stock_prediction_content(prediction_data, styles, heading_style))

    elif prediction_type == "investment_prediction":
        content.extend(_add_investment_prediction_content(prediction_data, styles, heading_style))

    elif prediction_type == "company_comparison":
        content.extend(_add_company_comparison_content(prediction_data, styles, heading_style))

    # -------- DISCLAIMER --------
    content.append(Spacer(1, 25))
    content.append(Paragraph("Disclaimer", heading_style))
    content.append(Paragraph(
        "This report is generated by AI algorithms for informational purposes only. "
        "It should not be considered financial advice.",
        styles["Normal"]
    ))

    doc.build(content)
    buffer.seek(0)
    return buffer

def _add_stock_prediction_content(data, styles, heading_style):
    content = []
    content.append(Paragraph("Prediction Summary", heading_style))

    d = data.get("prediction_details", {})

    table_data = [
        ["Metric", "Value"],
        ["Predicted Price", f"₹{data.get('predicted_price', 0):,.2f}"],
        ["Confidence Score", f"{data.get('confidence_score', 0):.1%}"],
        ["Model Type", data.get("model_type", "N/A")],
        ["Current Price", f"₹{d.get('latest_price', 0):,.2f}"],
        ["Predicted Change", f"₹{d.get('predicted_change', 0):,.2f}"],
        ["Change Percentage", f"{d.get('predicted_change_percent', 0):.2f}%"],
        ["Data Points Used", str(d.get("data_points_used", 0))]
    ]

    table = Table(table_data, hAlign="LEFT")
    _apply_table_style(table, header_color=colors.darkblue)

    content.append(table)
    content.append(Spacer(1, 20))
    return content

def _add_investment_prediction_content(data, styles, heading_style):
    content = []
    content.append(Paragraph("Investment Analysis", heading_style))

    table_data = [
        ["Metric", "Value"],
        ["Investment Amount", f"₹{data.get('investment_amount', 0):,.2f}"],
        ["Predicted Return", f"₹{data.get('predicted_return', 0):,.2f}"],
        ["Predicted Profit", f"₹{data.get('predicted_profit', 0):,.2f}"],
        ["Profit Percentage", f"{data.get('profit_percentage', 0):.2f}%"],
        ["Is Profitable", "Yes" if data.get("is_profitable") else "No"],
        ["Confidence Score", f"{data.get('confidence_score', 0):.1%}"],
        ["Time Horizon", format_time_horizon(data.get("time_horizon"))]
    ]

    table = Table(table_data, hAlign="LEFT")
    _apply_table_style(table, header_color=colors.darkgreen)

    content.append(table)
    content.append(Spacer(1, 20))
    return content


def _add_company_comparison_content(data, styles, heading_style):
    content = []
    content.append(Paragraph("Company Comparison", heading_style))

    details = data.get("comparison_details", {})

    table_data = [
        ["Metric", "Company 1", "Company 2"],
        [
            "Company Name",
            details.get("company1", {}).get("name", "N/A"),
            details.get("company2", {}).get("name", "N/A")
        ],
        [
            "Predicted Return",
            f"{data.get('company1_predicted_return', 0):.2f}%",
            f"{data.get('company2_predicted_return', 0):.2f}%"
        ],
        [
            "Recommended",
            "✓" if data.get("recommended_company") == 1 else "✗",
            "✓" if data.get("recommended_company") == 2 else "✗"
        ],
        [
            "Confidence Score",
            f"{data.get('confidence_score', 0):.1%}",
            f"{data.get('confidence_score', 0):.1%}"
        ],
        [
            "Time Horizon",
            format_time_horizon(data.get("time_horizon")),
            format_time_horizon(data.get("time_horizon"))
        ]
    ]

    table = Table(table_data, hAlign="CENTER")
    _apply_table_style(table, header_color=colors.darkblue)

    content.append(table)
    content.append(Spacer(1, 20))
    return content

def _apply_table_style(table, header_color):
    table.setStyle(TableStyle([
        ("BACKGROUND", (0, 0), (-1, 0), header_color),
        ("TEXTCOLOR", (0, 0), (-1, 0), colors.whitesmoke),
        ("ALIGN", (0, 0), (-1, -1), "CENTER"),
        ("GRID", (0, 0), (-1, -1), 1, colors.black),
        ("FONTNAME", (0, 0), (-1, 0), "Helvetica-Bold"),
        ("BOTTOMPADDING", (0, 0), (-1, 0), 10),
        ("TOPPADDING", (0, 0), (-1, 0), 10),
    ]))
